site_name: GraphCMS Docs
theme: 'material'
# Project information
site_description: 'A GraphQL based Headless Content Management System'
site_author: 'Michael Lukaszczyk & Daniel Winter'
site_url: 'https://graphcms.com'

# Documentation and theme
docs_dir: 'docs'
theme: 'material'
theme_dir: 'theme/material'
# Options
extra:
  version: '0.1.0'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  social:
    - type: 'github'
      link: 'https://github.com/graphcms'
    - type: 'twitter'
      link: 'https://twitter.com/graphcms'

# Copyright
copyright: 'Copyright &copy; 2017 GraphCMS'

extra_css:
  - 'stylesheets/extra.css'

# Extensions
markdown_extensions:
  - codehilite(css_class=code)
  - admonition
  - toc:
      permalink: '#'

pages:
- Introduction: 'index.md'
- Concepts: 'Concepts.md'
- Getting Started: 'Getting_Started.md'
- Media: 'Media.md'
- Webhooks: 'Webhooks.md'
- Examples:
  - 'Server-side rendered app with Next.js and Apollo': 'examples/Server-side_rendered_app_with_nextjs_and_apollo.md'
- Guides:
  - 'Export Schema and Content': 'guides/Export_schema_and_content.md'
  - 'Adding People to your project': 'guides/Adding_people_to_project.md'
- API:
  - 'Simple': 'API_simple.md'
  - 'Relay': 'API_relay.md'
