site_name: GraphCMS Docs
theme: 'material'
theme_dir: 'material'
# Project information
site_description: 'A GraphQL based Headless Content Management System'
site_author: 'Michael Lukaszczyk & Daniel Winter'
site_url: 'https://graphcms.com'

# Documentation and theme
docs_dir: 'docs'
theme: 'material'

# Options
extra:
  version: '0.1.0'
  #logo: 'images/logo.png'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Extensions
markdown_extensions:
  - codehilite(css_class=code)
  - admonition
  - toc:
      permalink: '#'

pages:
- Introduction: 'index.md'
- Getting Started: 'Getting_Started.md'
- Content Editing: 'Content_Editing.md'
- Connect: 'Connect.md'
- Examples: 'Examples.md'
