site_name: GraphCMS Docs
theme: 'material'
# Project information
site_description: 'A GraphQL based Headless Content Management System'
site_author: 'Michael Lukaszczyk & Daniel Winter'
site_url: 'https://graphcms.com/docs'

# Documentation and theme
docs_dir: 'docs'
theme: 'material'
theme_dir: 'theme/material'
# Options
extra:
  version: '0.1.0'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  social:
    - type: 'github'
      link: 'https://github.com/graphcms'
    - type: 'twitter'
      link: 'https://twitter.com/graph_cms'

# Copyright
copyright: 'Copyright &copy; 2017 GraphCMS'

extra_css:
  - 'stylesheets/extra.css'

# Extensions
markdown_extensions:
  - codehilite(css_class=code)
  - admonition
  - toc:
      permalink: '#'

pages:
- Introduction: 'index.md'
- Concepts: 'Concepts.md'
- Getting Started: 'Getting_Started.md'
- Assets: 'Assets.md'
- Webhooks: 'Webhooks.md'
- Examples:
  - 'Server-side rendered app with Next.js and Apollo': 'examples/Server-side_rendered_app_with_nextjs_and_apollo.md'
  - 'Star Wars App with Expo': 'examples/Star_Wars_Expo.md'
- Guides:
  - 'Adding Members to your Team': 'guides/Adding_members_to_team.md'
  - 'Using Permissions': 'guides/Using_Permissions.md'
  - 'Using Permanent Auth Tokens': 'guides/Using_permanent_auth_tokens.md'
  - 'Publishing Workflows': 'guides/Publishing_workflow.md'
  - 'Using Aliases for your API': 'guides/Using_aliases_for_api.md'
  - 'Export Schema and Content': 'guides/Export_schema_and_content.md'
  - 'Import simple data': 'guides/Import_simple_data.md'
  - 'Using Nested Mutations': 'guides/Using_Nested_Mutations.md'
- API:
  - 'Simple': 'API_simple.md'
  - 'Relay': 'API_relay.md'
