site_name: GraphCMS Docs
theme: 'material'
# Project information
site_description: 'A GraphQL based Headless Content Management System'
site_author: 'Michael Lukaszczyk & Daniel Winter'
site_url: 'https://graphcms.com/docs'

# Documentation and theme
docs_dir: 'docs'
theme: 'material'
theme_dir: 'theme/material'
# Options
extra:
  version: '0.1.0'
  logo: 'img/graphcms_logo.svg'
  font:
    text: 'Open Sans'
    code: 'Roboto Mono'
  social:
    - type: 'github'
      link: 'https://github.com/graphcms'
    - type: 'twitter'
      link: 'https://twitter.com/graph_cms'

# Copyright
copyright: 'Copyright &copy; 2017 GraphCMS'

extra_css:
  - 'stylesheets/extra.css'

# Extensions
markdown_extensions:
  - codehilite(css_class=code)
  - admonition
  - toc:
      permalink: '#'

pages:
- Introduction: 'Introduction.md'
- Concepts: 'Concepts.md'
- Getting Started: 
  - 'Setting up the Blog Example Project': 'getting-started/Setting_up_the_project.md'
  - 'Beginners Guide with React': 'getting-started/Beginners_Guide_With_React.md'
  - 'Beginners Guide with Vue': 'getting-started/Beginners_Guide_With_Vue.md'
- Assets:
  - 'General': 'assets/General.md'
  - 'Querying an Asset Field': 'assets/Querying_Assets_Field.md'
  - Transformations:
    - 'Transforming URL Structure': 'assets/Transforming_URL_Structure.md'
    - 'Resize Fit and Align' : 'assets/Resize_Fit_Align.md'
    - 'Crop' : 'assets/Crop.md'
    - 'Rotate': 'assets/Rotate.md'
    - 'Flip': 'assets/Flip.md'
    - 'Flop': 'assets/Flop.md'
    - 'Watermark': 'assets/Watermark.md'
    - Facial Detection:
      - 'Detect Faces': 'assets/facial_detection/Detect_Faces.md'
      - 'Crop Faces': 'assets/facial_detection/Crop_Faces.md'
      - 'Pixelate Faces': 'assets/facial_detection/Pixelate_Faces.md'
      - 'Blur Faces': 'assets/facial_detection/Blur_Faces.md'
    - 'Filetype Conversions': 'assets/Filetype_Conversions.md'
    - 'Compress': 'assets/Compress.md'
    - 'Change Quality': 'assets/Change_Quality.md'
  - 'Chaining Transformations': 'assets/Chanining_Transformations.md'
- Integrations:
  - 'integrations/Algolia.md'
- Examples:
  - 'Server-side rendered app with Next.js and Apollo': 'examples/Server-side_rendered_app_with_nextjs_and_apollo.md'
  - 'Star Wars App with Expo': 'examples/Star_Wars_Expo.md'
- Guides:
  - 'Adding Members to your Team': 'guides/Adding_members_to_team.md'
  - 'Using Permanent Auth Tokens': 'guides/Using_permanent_auth_tokens.md'
  - 'Publishing Workflows': 'guides/Publishing_workflow.md'
  - 'Using Aliases for your API': 'guides/Using_aliases_for_api.md'
  - 'Export Schema and Content': 'guides/Export_schema_and_content.md'
  - 'Import simple data': 'guides/Import_simple_data.md'
  - 'Using Nested Mutations': 'guides/Using_Nested_Mutations.md'
  - 'Changing Your Email and Password': 'guides/User_Settings.md'
  - 'Using Translations': 'guides/Using_translations.md'
  - 'Uploading Images to GraphCMS': 'guides/Uploading_images.md'
  - 'Import Contentful Projects': 'guides/Import_contentful_projects.md'
- API:
  - 'Simple': 'API_simple.md'
  - 'Relay': 'API_relay.md'
